### ISSUE TITLE
[Bugi] OUTI: Siirtoraportilla Internal Server Error -ilmoituksia

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/koha-plugin-exporter-report#1]
### Mikä vikana?

OUTIn siirtoraportin Keskeytyneet-sivulla on yli kymmenen sivua tietueita, joissa virheilmoitus: "Internal Server Error". Virheilmoituksia on tullut 29.10.2022 aamuyöllä noin klo 3.46 - 4.00 välillä. Ilmoituksia on tullut lisää 1.11.2022 klo 3.58.

1.11.2022 klo 9.20 on tullut tietueita virheilmoituksella: "Internal Server Error {"errors":[{"message":"Internal Server Error.","path":"\/"}],"status":500}" 

Mistähän nämä voisi johtua? 

### Kohan osio

Kuvailu

**Comment by CodoDerDritte** [comment]
ElasticSearch on pysäyksissä 3.45 alkaen indeksin varmuuskopioinnin vuoksi, eli hakukone ei ole tuohon aikaan käytettävissä. Luulen että tämä liittyy siihen. Valuneita tietueita on todennäköisesti yritetty tuolloin indeksoida, joka on epäonnistunut, koska haku on alhaalla.

**Comment by CodoDerDritte** [comment]
Kokeillaan muuttaa broadcast_biblio ajastusta siten että sitä ajetaan vain klo 06.00-23.58, jolloin nuo indeksivarmistukset saadaan ohiteltua.

**Comment by CodoDerDritte** [comment]
Jaa se onkin jo ajastettuna. Sitä ajetaan vain 07-21, eli ei ole tuo sitten ratkaisu tähän ongelmaan.

**Comment by CodoDerDritte** [comment]
Täytyy ilmeisesti pysäyttää TäTiltä Koha-Suomi Services, jottei se yritä valuttaa tietueita paikalliskantoihin silloin kun haku ei ole niissä käytettävissä. Tällä hetkellä Servicesin käynnistysskriptissä näyttää kuitenkin olevan bugi, jonka vuoksi se 

a) ei aina pysäytä Servicesiä oikein
b) antaa käynnistää rajattoman määrän kopioita Servicesistä, joka taas aiheuttaa kaikenlaista häröilyä paikalliskannoissa

Käynistysskriptiin täytyy kirjoittaa lukitus ja sen jälkeen ajastaa sen pysäytys ja käynnistys.

**Comment by emta001** [comment]
Mikä tämän tilanne on? Ratkaisu ehdotettu?

**Comment by CodoDerDritte** [comment]
Assignee puuttuu, mutta olen siis tehnyt tuohon valutukseen muutoksen, jolla se voidaan ajastaa.

**Comment by AnneliO** [comment]
OUTIn siirtoraportilla näyttäisi olevan taas näitä:



Aikaleima | Tapahtuma | Tietuenumero | Tätin tietuenumero | Virhe
-- | -- | -- | -- | --
13.2.2023 9:05:57 | Uusi |   | 519482 | Internal Server Error {"errors":[{"message":"Internal Server Error.","path":"\/"}],"status":500}
13.2.2023 9:05:57 | Uusi |   | 519483 | Internal Server Error {"errors":[{"message":"Internal Server Error.","path":"\/"}],"status":500}
13.2.2023 9:05:56 | Uusi |   | 519477 | Internal Server Error {"errors":[{"message":"Internal Server Error.","path":"\/"}],"status":500}
13.2.2023 9:05:56 | Uusi |   | 519478 | Internal Server Error {"errors":[{"message":"Internal Server Error.","path":"\/"}],"status":500}
13.2.2023 9:05:56 | Uusi |   | 519479 | Internal Server Error {"errors":[{"message":"Internal Server Error.","path":"\/"}],"status":500}
13.2.2023 9:05:56 | Uusi |   | 519480 | Internal Server Error {"errors":[{"message":"Internal Server Error.","path":"\/"}],"status":500}
13.2.2023 9:05:56 | Uusi |   | 519481 | Internal Server Error {"errors":[{"message":"Internal Server Error.","path":"\/"}],"status":500}
13.2.2023 9:05:55 | Uusi |   | 519472 | Internal Server Error {"errors":[{"message":"Internal Server Error.","path":"\/"}],"status":500}
13.2.2023 9:05:55 | Uusi |   | 519473 | Internal Server Error {"errors":[{"message":"Internal Server Error.","path":"\/"}],"status":500}



Esim. tuo eka tietue [519482](https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=519482) ei ole muuttunut Tätissä sitten vuoden 2014 ja OUTIssa sitten vuoden 2022, joten miksi lie valumista on edes yritetty.

**Comment by AnneliO** [comment]
OUTIn siirtoraportilla näkyi taas noita Internal Server Erroreita lisämausteilla 12.6.2023 8:18 aikoihin. Ne liittyivät osakohteisiin, joiden tuonti paikalliskantaan oli epäonnistunut. Emotietueessa oli Tätissä kiinni ylimääräisiä osakohteita, joissa 773w-kentässä oli väärä tietuenumero. Osakohteet olivat tuplia, sillä niiden oikealla emolla oli osakohteet, mutta eri tietuenumeroilla.

Eli Nelma U:lla oli liikaa poikasia: https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2331802

Ylimääräiset poikaset väittivät kuuluvansa tälle: https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2341357

Olen pyytänyt kuvailijoita korjaamaan tilanteen. En nyt tiedä, johtuiko tuo virhetilanne noista virheellisesti linkittyvistä osakohteista, mutta ei ne ainakaan varmasti auta asiaa. Niin ja kummallekaan noista linkatuista teoksista ei ollut valunut poikaset paikalliskantaan.

**Comment by pirliis** [comment]
OUTIssa ei ole enää 14.8.2023 jälkeen tullut noita Internal Server Erroreita siirtoraportille

Samaa ongelmaa on käsitelty tiketissä https://github.com/KohaSuomi/Koha/issues/728, joka on suljettu. 

Suljen tämänkin tältä erää ja avataan tarvittaessa uudestaan.
