### ISSUE TITLE
Siirtoraportilla tiedot menevät päällekkäin

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/koha-plugin-exporter-report#2]
### Mikä vikana?

Siirtoraportilla muutokset popupissa pitkät merkkijonot valuvat toisen sarakkeen päälle.

### Mitä pitäisi tapahtua

Pitkät merkkijonot saisivat rivittyä, kun niiltä loppuu tila sarakkeessaan.

### Jotain muuta?

![Siirtoraportin ongelma](https://github.com/KohaSuomi/Koha/assets/98884651/584e88ca-b598-42fb-ab70-d0a62fb17b32)

**Comment by johannaraisa** [comment]
Onko tämä ok, suljetko tiketin?

**Comment by MikkoLiimatainen** [comment]
Näyttäisi olevan ok.
